### ISSUE TITLE
Lucene search scheduled indexing job does not index

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-lucene-search#4]
The Hangfire indexing job shows as successful, but the indexes are not updated.  If I re-build the indexes manually through the platform admin, it indexes successfully.

Platform version 2.13.27
Module version 1.1.0

@IgorisB

**Comment by tatarincev** [comment]
@benb1n  Which kind of catalog data was changed, but wasn't indexed by the job?

**Comment by benb1n** [comment]
@tatarincev Member data.  I noticed that it's acting the same way if I plug in Azure search, so it doesn't appear to be specific to Lucene.  The background indexing job has been running successfully according to Hangfire, but it's not indexing any new changes.

**Comment by benb1n** [comment]
@tatarincev Any update or guidance on this?  This is another issue we need a resolution or workaround for quickly.

**Comment by tatarincev** [comment]
@benb1n I'll definitely check it tomorrow, excuse me for the delay.

**Comment by benb1n** [comment]
@tatarincev I just noticed that Products are indexing.  It's just members that don't index.

**Comment by tatarincev** [comment]
@Benb1n VC Platform has 'IndexingJobs.IndexChangesJob', which responsible for indexing all **modified** objects belonging to the modules, for example, Catalog, Customer, and so on. The basic precondition for this, an indexing entity should be changed through API or the relevant service from code and has a record in the table `[PlatformOperationLog]` with a new modification date.
In your case how you did these members changes? Or maybe can you provide steps or other information how can I reproduce this issue?

**Comment by benb1n** [comment]
@tatarincev  If I create a new Member of any type from platform, the search index widget shows that the search index is missing.  Once the indexing job runs, it still shows as index missing and the member does not show in the search results.  If I click the option from the widget to manually index, it properly indexes it.  If I run a Build of the indexes from the Search Index module, it also indexes it properly (along with everything else).  So it seems that the indexing job is not picking up change notifications for Members.

I have also tested just changing first name or last name on existing members, and the index is not updated by the job either.

If I check the `PlatformOperationLog` table, I don't see any entries for these new members.  I do see records for new users/accounts created in the storefront, but it's for the `ApplicationUserExtended` type only, not for the contact type.  I don't think those are part of the Members search index anyhow.

Hope that helps.  Let me know if you need any other details.

**Comment by benb1n** [comment]
@tatarincev This ended up being a mistake on my part.  I have a custom Repository implementation for some derived Member types.  When I registered the repo factory, I followed a different example instead of looking at the base Customer module, and I didn't include the `ChangeLogInterceptor`.  My bad!  I'll close this issue.  Thanks for your help on it!
