### ISSUE TITLE
Lucene search doesn't filter aggregations in search result

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-lucene-search#6]
Search always return all not filtered aggregations for any request. 
How to reproduce:
Call `POST  api/catalog/search/products`
with 
```JSON
{
"store": "Electronics",
"searchPhrase": "xyz",
"skip": 0,
"take": 20
}
``` 
Got response with 0 found items but `response.aggregations` will contains a list of aggregation items for all products stored in the index,

**Comment by kostyrin** [comment]
have to use storeId
typo: storeId

try to 
```
{
"storeId": "Electronics",
"searchPhrase": "BLU",
"skip": 0,
"take": 20
}
```
request:
![image](https://user-images.githubusercontent.com/8361000/62290729-548f8f80-b462-11e9-8ac4-952a44dbe42b.png)

response
![image](https://user-images.githubusercontent.com/8361000/62290696-3c1f7500-b462-11e9-97eb-9761a92de1c1.png)

**Comment by tatarincev** [comment]
but this is not right behavior, isn't? Why search returns the aggregations with counts for empty search result!

**Comment by akak1977** [comment]
Non-actual anymore
